# Generated by Django 4.2.2 on 2023-10-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='orden',
        ),
        migrations.AddField(
            model_name='orden',
            name='plato',
            field=models.ManyToManyField(to='Clientes.plato'),
        ),
    ]
